export const filters = new Map([
    ["Essen und Trinken", "food_and_drinks"],
    ["Essen", "food"],
    ["Restaurant", "restaurant"],
    ["Fast Food Restaurant", "fast_food"],
    ["Café", "cafe"],
    ["Eisdiele", "ice_cream"],
    ["Bar", "bar"],
    ["Pub", "pub"],
    ["Club", "nightlife"],
    ["Biergarten", "biergarten"],

    ["Touristenattraktion", "tourist_attraction"],
    ["Spielplatz", "playground"],
    ["Garten", "garden"],
    ["Monument", "monument"],
    ["Zoo", "zoo"],
    ["Aquarium", "aquarium"],
    ["Park", "park"],
    ["See", "lake"],
    ["Berg", "mountain"],
    ["Schwimmbad", "swimming_pool"],
    ["Veranstaltungsfläche", "event_space"],
    ["Vergnügungspark", "theme_park_attraction"],
    ["Sportplatz", "field"],
    ["Basketball", "basketball_court"],
    ["Fussballplatz", "soccer_field"],
    ["Minigolf", "miniature_golf"],
    ["Go-Kart", "go_kart_racing"],
    ["Billard", "billiards"],
    ["Laser-Tag", "laser_tag"],
    ["Kino", "cinema"],
    ["Arkade", "arcade"],
    ["Museum", "museum"],
    ["Unterhaltung", "entertainment"],
    ["Musikveranstaltungen", "music_venue"],

    ["Einkaufen", "shopping"], 
    ["Einkaufszentrum", "shopping_mall"],
    ["Schuhladen", "shoe_store"],
    ["Kosmetik", "beauty_store"],
    ["Kleidung", "clothing_store"],
]);